 
let Data=[
    {
     "proId": "p101",
     "image": "../Assests/furniturePhotos/1.jpeg",
     "sImages": "null",
     "oldPrice": 1999,
     "newPrice": 1499,
     "category": "chair",
     "sCategory": "Stool",
     "stock": 54,
     "title": "Student Study Chair For Learning",
     "description": "Student Study Chair - New design Student Study Chair with cushion seating and flexible wooden writing pad gives amazing comfort while studying.",
     "specification": "Best sofa For Office Reception with Backrest and Armrest"
    },
    {
     "proId": "p102",
     "image": "../Assests/furniturePhotos/2.jpeg",
     "sImages": "null",
     "oldPrice": 5999,
     "newPrice": 5499,
     "category": "table ",
     "sCategory": "FoldingTable",
     "stock": 45,
     "title": "Full Wooden Writingpad Chair ",
     "description": "Full Wooden Writingpad Chair ",
     "specification": "Kylin Revolving Office Chair in Black - Fixed Handle - Mid-Back - Plastic Base, Net Seat and Back For Office, Workstation In Black Color."
    },
    {
     "proId": "p103",
     "image": "../Assests/furniturePhotos/3.jpeg",
     "sImages": "null",
     "oldPrice": 11999,
     "newPrice": 11499,
     "category": "wordrobe",
     "sCategory": "wordrobe",
     "stock": 54,
     "title": "Wooden Writing Pad Chair in Brown",
     "description": "Writing pad fabric study chair - Best black cushion writing pad chair with half pad and designer looking fix arm pad chair in black colour",
     "specification": "Italica Chair 2109: Designed specifically to support the vertebral column and to provide excellent lumbar support, the spine care series is the finest specimen of ergonomic design, aesthetics and comfort."
    },
    {
     "proId": "p104",
     "image": "../Assests/furniturePhotos/4.jpeg",
     "sImages": "null",
     "oldPrice": 8922,
     "newPrice": 8422,
     "category": "bed ",
     "sCategory": "SofaBed",
     "stock": 54,
     "title": "Writing Pad Chair with Cushion Seat in Black",
     "description": "Study Chair with Writing Pad Folding arm, cushion seat, chrome frame half brown writing pad plastic withholding stuff under the chair.",
     "specification": "Best sofa For Office Reception with Backrest and Armrest"
    },
    {
     "proId": "p105",
     "image": "../Assests/furniturePhotos/5.jpeg",
     "sImages": "null",
     "oldPrice": 9895,
     "newPrice": 9395,
     "category": "desk",
     "sCategory": "desk",
     "stock": 54,
     "title": "Wooden Study Pad Chair Joint Seat and Back",
     "description": "New design flexible writing board chair with cushion blue seating and flexible wooden writing pad.",
     "specification": "This office sofa set comes with a geometric design. the brown sofa with a backrest and armrest you to experience superior comfort."
    },
    {
     "proId": "p106",
     "image": "../Assests/furniturePhotos/6.jpeg",
     "sImages": "null",
     "oldPrice": 55562,
     "newPrice": 55062,
     "category": "bookcase",
     "sCategory": "bookcase",
     "stock": 78,
     "title": "Writing Pad Fabric Study Chair for Self Study, Cushion Seat and Back",
     "description": "Writing pad fabric study chair - Best black cushion writing pad chair with half pad and designer looking fix arm pad chair in black colour",
     "specification": "This Couch Office - Couch for Office in Black"
    },
    {
     "proId": "p107",
     "image": "../Assests/furniturePhotos/7.jpeg",
     "sImages": "null",
     "oldPrice": 56665,
     "newPrice": 56165,
     "category": "chair",
     "sCategory": "Arm Chair",
     "stock": 78,
     "title": "Study Chair with Writing Pad",
     "description": "Study Chair with Writing Pad Folding arm, cushion seat, chrome frame half brown writing pad plastic withholding stuff under the chair.",
     "specification": "Supreme Omega Chair - Plastic Chair Design: Contemporary stackable design with premium and classy rattan-finish."
    },
    {
     "proId": "p108",
     "image": "../Assests/furniturePhotos/8.jpeg",
     "sImages": "null",
     "oldPrice": 26552,
     "newPrice": 26052,
     "category": "table ",
     "sCategory": "FoldingTable",
     "stock": 54,
     "title": "Writing Pad Chair with Cushion Seat in Black",
     "description": "New design flexible writing board chair with cushion blue seating and flexible wooden writing pad.",
     "specification": "Italica Chair 2109: Designed specifically to support the vertebral column and to provide excellent lumbar support, the spine care series is the finest specimen of ergonomic design, aesthetics and comfort."
    },
    {
     "proId": "p109",
     "image": "../Assests/furniturePhotos/9.jpeg",
     "sImages": "null",
     "oldPrice": 56202,
     "newPrice": 55702,
     "category": "wordrobe",
     "sCategory": "wordrobe",
     "stock": 66,
     "title": "New Design Writingpad Chair",
     "description": "Writing pad fabric study chair - Best black cushion writing pad chair with half pad and designer looking fix arm pad chair in black colour",
     "specification": "Kylin Revolving Office Chair in Black - Fixed Handle - Mid-Back - Plastic Base, Net Seat and Back For Office, Workstation In Black Color."
    },
    {
     "proId": "p110",
     "image": "../Assests/furniturePhotos/10.jpeg",
     "sImages": "null",
     "oldPrice": 87004,
     "newPrice": 86504,
     "category": "bed ",
     "sCategory": "SofaBed",
     "stock": 545,
     "title": "Round Restaurant Table ",
     "description": "Disc Supreme Restaurant Round Table.  pad chair with half pad and designer looking fix arm pad chair in black colour",
     "specification": "3 Seater Sofa For Office Reception with caution and black colour."
    },
    {
     "proId": "p111",
     "image": "../Assests/furniturePhotos/11.jpeg",
     "sImages": "null",
     "oldPrice": 4541,
     "newPrice": 4041,
     "category": "desk",
     "sCategory": "desk",
     "stock": 54,
     "title": "Sunmica Marble Top",
     "description": "This Couch Office - Couch for Office in Black",
     "specification": "Italica 8103 Chair - Outdoor Luxury Sunlounger Chair by Kylin"
    },
    {
     "proId": "p112",
     "image": "../Assests/furniturePhotos/12.jpeg",
     "sImages": "null",
     "oldPrice": 5562,
     "newPrice": 5062,
     "category": "bookcase",
     "sCategory": "bookcase",
     "stock": 45,
     "title": "Supreme Disc Plastic Round Table",
     "description": "Italica Chair 2109: Designed specifically to support the vertebral column and to provide excellent lumbar support, the spine care series is the finest specimen of ergonomic design, aesthetics and comfort.",
     "specification": "This office sofa set comes with a geometric design. the brown sofa with a backrest and armrest you to experience superior comfort."
    },
    {
     "proId": "p113",
     "image": "../Assests/furniturePhotos/13.jpeg",
     "sImages": "null",
     "oldPrice": 5265,
     "newPrice": 4765,
     "category": "chair",
     "sCategory": "Dinning Chair",
     "stock": 54,
     "title": "Stainless Steel Dining Table",
     "description": "This office sofa set comes with a geometric design. the brown sofa with a backrest and armrest you to experience superior comfort.",
     "specification": "3 Seater Sofa For Office Reception with caution and black colour."
    },
    {
     "proId": "p114",
     "image": "../Assests/furniturePhotos/14.jpeg",
     "sImages": "null",
     "oldPrice": 1546,
     "newPrice": 1046,
     "category": "table ",
     "sCategory": "FoldingTable",
     "stock": 54,
     "title": "Designer Italica Arm Chair with Steel Leg",
     "description": "This Couch Office - Couch for Office in Black",
     "specification": "Best sofa For Office Reception with Backrest and Armrest"
    },
    {
     "proId": "p115",
     "image": "../Assests/furniturePhotos/15.jpeg",
     "sImages": "null",
     "oldPrice": 4650,
     "newPrice": 4150,
     "category": "wordrobe",
     "sCategory": "wordrobe",
     "stock": 54,
     "title": "Stainless Steel Dining Table",
     "description": "Italica 8103 Chair - Outdoor Luxury Sunlounger Chair by Kylin",
     "specification": "Kylin Revolving Office Chair in Black - Fixed Handle - Mid-Back - Plastic Base, Net Seat and Back For Office, Workstation In Black Color."
    },
    {
     "proId": "p116",
     "image": "../Assests/furniturePhotos/16.jpeg",
     "sImages": "null",
     "oldPrice": 1999,
     "newPrice": 1499,
     "category": "bed ",
     "sCategory": "SofaBed",
     "stock": 78,
     "title": "Restaurant Dining Table for Restaurant",
     "description": "Best sofa For Office Reception with Backrest and Armrest",
     "specification": "Best sofa For Office Reception with Backrest and Armrest"
    },
    {
     "proId": "p117",
     "image": "../Assests/furniturePhotos/17.jpeg",
     "sImages": "null",
     "oldPrice": 5999,
     "newPrice": 5499,
     "category": "desk",
     "sCategory": "desk",
     "stock": 78,
     "title": "Sun lounger Chair - Outdoor Luxury Sun lounger",
     "description": "Best sofa For Office Reception with Backrest and Armrest",
     "specification": "Italica Chair 2109: Designed specifically to support the vertebral column and to provide excellent lumbar support, the spine care series is the finest specimen of ergonomic design, aesthetics and comfort."
    },
    {
     "proId": "p118",
     "image": "../Assests/furniturePhotos/18.jpeg",
     "sImages": "null",
     "oldPrice": 11999,
     "newPrice": 11499,
     "category": "bookcase",
     "sCategory": "bookcase",
     "stock": 54,
     "title": "Stainless Steel Dining Table",
     "description": "This office sofa set comes with a geometric design. the brown sofa with a backrest and armrest you to experience superior comfort.",
     "specification": "Supreme Omega Chair - Plastic Chair Design: Contemporary stackable design with premium and classy rattan-finish."
    },
    {
     "proId": "p119",
     "image": "../Assests/furniturePhotos/19.jpeg",
     "sImages": "null",
     "oldPrice": 8922,
     "newPrice": 8422,
     "category": "chair",
     "sCategory": "Dinning Chair",
     "stock": 66,
     "title": "Italica 9313 Chair",
     "description": "This Couch Office - Couch for Office in Black",
     "specification": "This Couch Office - Couch for Office in Black"
    },
    {
     "proId": "p120",
     "image": "../Assests/furniturePhotos/20.jpeg",
     "sImages": "null",
     "oldPrice": 9895,
     "newPrice": 9395,
     "category": "table ",
     "sCategory": "FoldingTable",
     "stock": 545,
     "title": "Italica Chair in Plastic Body",
     "description": "Italica Chair 2109: Designed specifically to support the vertebral column and to provide excellent lumbar support, the spine care series is the finest specimen of ergonomic design, aesthetics and comfort.",
     "specification": "Kylin Revolving Office Chair in Black - Fixed Handle - Mid-Back - Plastic Base, Net Seat and Back For Office, Workstation In Black Color."
    },
    {
     "proId": "p121",
     "image": "../Assests/furniturePhotos/21.jpeg",
     "sImages": "null",
     "oldPrice": 55562,
     "newPrice": 55062,
     "category": "wordrobe",
     "sCategory": "wordrobe",
     "stock": 54,
     "title": "Restaurant Dining Table for Restaurant",
     "description": "Kylin Revolving Office Chair in Black - Fixed Handle - Mid-Back - Plastic Base, Net Seat and Back For Office, Workstation In Black Color.",
     "specification": "Best sofa For Office Reception with Backrest and Armrest"
    },
    {
     "proId": "p122",
     "image": "../Assests/furniturePhotos/22.jpeg",
     "sImages": "null",
     "oldPrice": 56665,
     "newPrice": 56165,
     "category": "bed ",
     "sCategory": "SofaBed",
     "stock": 45,
     "title": "Italica Chair in Plastic Body",
     "description": "This office sofa set comes with a geometric design. the brown sofa with a backrest and armrest you to experience superior comfort.",
     "specification": "This office sofa set comes with a geometric design. the brown sofa with a backrest and armrest you to experience superior comfort."
    },
    {
     "proId": "p123",
     "image": "../Assests/furniturePhotos/23.jpeg",
     "sImages": "null",
     "oldPrice": 26552,
     "newPrice": 26052,
     "category": "desk",
     "sCategory": "desk",
     "stock": 54,
     "title": "Designer Italica Arm Chair with Steel Leg",
     "description": "This Couch Office - Couch for Office in Black",
     "specification": "This office sofa set comes with a geometric design. the brown sofa with a backrest and armrest you to experience superior comfort."
    },
    {
     "proId": "p124",
     "image": "../Assests/furniturePhotos/24.jpeg",
     "sImages": "null",
     "oldPrice": 56202,
     "newPrice": 55702,
     "category": "bookcase",
     "sCategory": "bookcase",
     "stock": 54,
     "title": "Chair With Side Arms (Camel)",
     "description": "Italica 8103 Chair - Outdoor Luxury Sunlounger Chair by Kylin",
     "specification": "3 Seater Sofa For Office Reception with caution and black colour."
    },
    {
     "proId": "p125",
     "image": "../Assests/furniturePhotos/25.jpeg",
     "sImages": "null",
     "oldPrice": 87004,
     "newPrice": 86504,
     "category": "chair",
     "sCategory": "Arm Chair",
     "stock": 54,
     "title": "Sun lounger Chair ",
     "description": "This office sofa set comes with a geometric design. the brown sofa with a backrest and armrest you to experience superior comfort.",
     "specification": "Italica 8103 Chair - Outdoor Luxury Sunlounger Chair by Kylin"
    },
    {
     "proId": "p126",
     "image": "../Assests/furniturePhotos/26.jpeg",
     "sImages": "null",
     "oldPrice": 4541,
     "newPrice": 4041,
     "category": "table ",
     "sCategory": "FoldingTable",
     "stock": 78,
     "title": "Sun lounger Chair - Outdoor Luxury Sun lounger",
     "description": "Kylin Revolving Office Chair in Black - Fixed Handle - Mid-Back - Plastic Base, Net Seat and Back For Office, Workstation In Black Color.",
     "specification": "3 Seater Sofa For Office Reception with caution and black colour."
    },
    {
     "proId": "p127",
     "image": "../Assests/furniturePhotos/27.jpeg",
     "sImages": "null",
     "oldPrice": 5562,
     "newPrice": 5062,
     "category": "wordrobe",
     "sCategory": "wordrobe",
     "stock": 78,
     "title": "Italica 9313 Chair",
     "description": "Best sofa For Office Reception with Backrest and Armrest",
     "specification": "This office sofa set comes with a geometric design. the brown sofa with a backrest and armrest you to experience superior comfort."
    },
    {
     "proId": "p128",
     "image": "../Assests/furniturePhotos/28.jpeg",
     "sImages": "null",
     "oldPrice": 5265,
     "newPrice": 4765,
     "category": "bed ",
     "sCategory": "SofaBed",
     "stock": 54,
     "title": "Sun lounger Chair ",
     "description": "Italica Chair 2109: Designed specifically to support the vertebral column and to provide excellent lumbar support, the spine care series is the finest specimen of ergonomic design, aesthetics and comfort.",
     "specification": "3 Seater Sofa For Office Reception with caution and black colour."
    },
    {
     "proId": "p129",
     "image": "../Assests/furniturePhotos/29.jpeg",
     "sImages": "null",
     "oldPrice": 1546,
     "newPrice": 1046,
     "category": "desk",
     "sCategory": "desk",
     "stock": 66,
     "title": "Best Outdoor Chair by Italica",
     "description": "Supreme Omega Chair - Plastic Chair Design: Contemporary stackable design with premium and classy rattan-finish.",
     "specification": "Kylin Revolving Office Chair in Black - Fixed Handle - Mid-Back - Plastic Base, Net Seat and Back For Office, Workstation In Black Color."
    },
    {
     "proId": "p130",
     "image": "../Assests/furniturePhotos/30.jpeg",
     "sImages": "null",
     "oldPrice": 4650,
     "newPrice": 4150,
     "category": "bookcase",
     "sCategory": "bookcase",
     "stock": 545,
     "title": "Italica Chair in Plastic Body",
     "description": "This Couch Office - Couch for Office in Black",
     "specification": "Best sofa For Office Reception with Backrest and Armrest"
    },
    {
     "proId": "p131",
     "image": "../Assests/furniturePhotos/31.jpeg",
     "sImages": "null",
     "oldPrice": 1999,
     "newPrice": 1499,
     "category": "chair",
     "sCategory": "Dinning Chair",
     "stock": 54,
     "title": "Italica 9313 Chair",
     "description": "Kylin Revolving Office Chair in Black - Fixed Handle - Mid-Back - Plastic Base, Net Seat and Back For Office, Workstation In Black Color.",
     "specification": "Italica Chair 2109: Designed specifically to support the vertebral column and to provide excellent lumbar support, the spine care series is the finest specimen of ergonomic design, aesthetics and comfort."
    },
    {
     "proId": "p132",
     "image": "../Assests/furniturePhotos/32.jpeg",
     "sImages": "null",
     "oldPrice": 5999,
     "newPrice": 5499,
     "category": "table ",
     "sCategory": "FoldingTable",
     "stock": 45,
     "title": "Restaurant Dining Table for Restaurant",
     "description": "Best sofa For Office Reception with Backrest and Armrest",
     "specification": "This office sofa set comes with a geometric design. the brown sofa with a backrest and armrest you to experience superior comfort."
    },
    {
     "proId": "p133",
     "image": "../Assests/furniturePhotos/33.jpeg",
     "sImages": "null",
     "oldPrice": 11999,
     "newPrice": 11499,
     "category": "wordrobe",
     "sCategory": "wordrobe",
     "stock": 54,
     "title": "Best Outdoor Chair by Italica",
     "description": "Italica Chair 2109: Designed specifically to support the vertebral column and to provide excellent lumbar support, the spine care series is the finest specimen of ergonomic design, aesthetics and comfort.",
     "specification": "3 Seater Sofa For Office Reception with caution and black colour."
    },
    {
     "proId": "p134",
     "image": "../Assests/furniturePhotos/34.jpeg",
     "sImages": "null",
     "oldPrice": 8922,
     "newPrice": 8422,
     "category": "bed ",
     "sCategory": "SofaBed",
     "stock": 54,
     "title": "Italica Chair in Plastic Body",
     "description": "This office sofa set comes with a geometric design. the brown sofa with a backrest and armrest you to experience superior comfort.",
     "specification": "Writing pad fabric study chair - Best black cushion writing pad chair with half pad and designer looking fix arm pad chair in black colour"
    },
    {
     "proId": "p135",
     "image": "../Assests/furniturePhotos/35.jpeg",
     "sImages": "null",
     "oldPrice": 9895,
     "newPrice": 9395,
     "category": "desk",
     "sCategory": "desk",
     "stock": 54,
     "title": "Sun lounger Chair - Outdoor Luxury Sun lounger",
     "description": "Best sofa For Office Reception with Backrest and Armrest",
     "specification": "Study Chair with Writing Pad Folding arm, cushion seat, chrome frame half brown writing pad plastic withholding stuff under the chair."
    },
    {
     "proId": "p136",
     "image": "../Assests/furniturePhotos/36.jpeg",
     "sImages": "null",
     "oldPrice": 55562,
     "newPrice": 55062,
     "category": "bookcase",
     "sCategory": "bookcase",
     "stock": 78,
     "title": "Restaurant Dining Table for Restaurant",
     "description": "Supreme Omega Chair - Plastic Chair Design: Contemporary stackable design with premium and classy rattan-finish.",
     "specification": "New design flexible writing board chair with cushion blue seating and flexible wooden writing pad."
    },
    {
     "proId": "p137",
     "image": "../Assests/furniturePhotos/37.jpeg",
     "sImages": "null",
     "oldPrice": 56665,
     "newPrice": 56165,
     "category": "chair",
     "sCategory": "Dinning Chair",
     "stock": 78,
     "title": "Italica 9313 Chair",
     "description": "Italica 8103 Chair - Outdoor Luxury Sunlounger Chair by Kylin",
     "specification": "Writing pad fabric study chair - Best black cushion writing pad chair with half pad and designer looking fix arm pad chair in black colour"
    },
    {
     "proId": "p138",
     "image": "../Assests/furniturePhotos/38.jpeg",
     "sImages": "null",
     "oldPrice": 26552,
     "newPrice": 26052,
     "category": "table ",
     "sCategory": "table",
     "stock": 54,
     "title": "Sun lounger Chair ",
     "description": "This Couch Office - Couch for Office in Black",
     "specification": "Disc Supreme Restaurant Round Table.  pad chair with half pad and designer looking fix arm pad chair in black colour"
    },
    {
     "proId": "p139",
     "image": "../Assests/furniturePhotos/39.jpeg",
     "sImages": "null",
     "oldPrice": 56202,
     "newPrice": 55702,
     "category": "wordrobe",
     "sCategory": "wordrobe",
     "stock": 66,
     "title": "Chair With Side Arms (Camel)",
     "description": "Kylin Revolving Office Chair in Black - Fixed Handle - Mid-Back - Plastic Base, Net Seat and Back For Office, Workstation In Black Color.",
     "specification": "This Couch Office - Couch for Office in Black"
    },
    {
     "proId": "p140",
     "image": "../Assests/furniturePhotos/40.jpeg",
     "sImages": "null",
     "oldPrice": 87004,
     "newPrice": 86504,
     "category": "bed ",
     "sCategory": "SofaBed",
     "stock": 54,
     "title": "Designer Italica Arm Chair with Steel Leg",
     "description": "Best sofa For Office Reception with Backrest and Armrest",
     "specification": "Italica Chair 2109: Designed specifically to support the vertebral column and to provide excellent lumbar support, the spine care series is the finest specimen of ergonomic design, aesthetics and comfort."
    },
    {
     "proId": "p141",
     "image": "../Assests/furniturePhotos/41.jpeg",
     "sImages": "null",
     "oldPrice": 4541,
     "newPrice": 4041,
     "category": "desk",
     "sCategory": "desk",
     "stock": 45,
     "title": "Best Outdoor Chair by Italica",
     "description": "Kylin Revolving Office Chair in Black - Fixed Handle - Mid-Back - Plastic Base, Net Seat and Back For Office, Workstation In Black Color.",
     "specification": "This office sofa set comes with a geometric design. the brown sofa with a backrest and armrest you to experience superior comfort."
    },
    {
     "proId": "p142",
     "image": "../Assests/furniturePhotos/42.jpeg",
     "sImages": "null",
     "oldPrice": 5562,
     "newPrice": 5062,
     "category": "bookcase",
     "sCategory": "bookcase",
     "stock": 54,
     "title": "Stainless Steel Dining Table",
     "description": "Italica Chair 2109: Designed specifically to support the vertebral column and to provide excellent lumbar support, the spine care series is the finest specimen of ergonomic design, aesthetics and comfort.",
     "specification": "This Couch Office - Couch for Office in Black"
    },
    {
     "proId": "p143",
     "image": "../Assests/furniturePhotos/43.jpeg",
     "sImages": "null",
     "oldPrice": 5265,
     "newPrice": 4765,
     "category": "chair",
     "sCategory": "Arm Chair",
     "stock": 54,
     "title": "Italica Chair in Plastic Body",
     "description": "Best sofa For Office Reception with Backrest and Armrest",
     "specification": "Italica 8103 Chair - Outdoor Luxury Sunlounger Chair by Kylin"
    },
    {
     "proId": "p144",
     "image": "../Assests/furniturePhotos/44.jpeg",
     "sImages": "null",
     "oldPrice": 1546,
     "newPrice": 1046,
     "category": "table ",
     "sCategory": "FoldingTable",
     "stock": 54,
     "title": "Stainless Steel Dining Table",
     "description": "This office sofa set comes with a geometric design. the brown sofa with a backrest and armrest you to experience superior comfort.",
     "specification": "This office sofa set comes with a geometric design. the brown sofa with a backrest and armrest you to experience superior comfort."
    },
    {
     "proId": "p145",
     "image": "../Assests/furniturePhotos/45.jpeg",
     "sImages": "null",
     "oldPrice": 4650,
     "newPrice": 4150,
     "category": "wordrobe",
     "sCategory": "wordrobe",
     "stock": 78,
     "title": "Chair With Side Arms (Camel)",
     "description": "This Couch Office - Couch for Office in Black",
     "specification": "Kylin Revolving Office Chair in Black - Fixed Handle - Mid-Back - Plastic Base, Net Seat and Back For Office, Workstation In Black Color."
    },
    {
     "proId": "p146",
     "image": "../Assests/furniturePhotos/46.jpeg",
     "sImages": "null",
     "oldPrice": 1999,
     "newPrice": 1499,
     "category": "bed ",
     "sCategory": "SofaBed",
     "stock": 78,
     "title": "Restaurant Dining Table for Restaurant",
     "description": "Supreme Omega Chair - Plastic Chair Design: Contemporary stackable design with premium and classy rattan-finish.",
     "specification": "Best sofa For Office Reception with Backrest and Armrest"
    },
    {
     "proId": "p147",
     "image": "../Assests/furniturePhotos/47.jpeg",
     "sImages": "null",
     "oldPrice": 5999,
     "newPrice": 5499,
     "category": "desk",
     "sCategory": "desk",
     "stock": 54,
     "title": "Italica Chair in Plastic Body",
     "description": "Italica Chair 2109: Designed specifically to support the vertebral column and to provide excellent lumbar support, the spine care series is the finest specimen of ergonomic design, aesthetics and comfort.",
     "specification": "This office sofa set comes with a geometric design. the brown sofa with a backrest and armrest you to experience superior comfort."
    },
    {
     "proId": "p148",
     "image": "../Assests/furniturePhotos/1.jpeg",
     "sImages": "null",
     "oldPrice": 11999,
     "newPrice": 11499,
     "category": "bookcase",
     "sCategory": "bookcase",
     "stock": 66,
     "title": "Designer Italica Arm Chair with Steel Leg",
     "description": "Kylin Revolving Office Chair in Black - Fixed Handle - Mid-Back - Plastic Base, Net Seat and Back For Office, Workstation In Black Color.",
     "specification": "This office sofa set comes with a geometric design. the brown sofa with a backrest and armrest you to experience superior comfort."
    },
    {
     "proId": "p149",
     "image": "../Assests/furniturePhotos/2.jpeg",
     "sImages": "null",
     "oldPrice": 8922,
     "newPrice": 8422,
     "category": "chair",
     "sCategory": "Dinning Chair",
     "stock": 545,
     "title": "Restaurant Dining Table for Restaurant",
     "description": "Best sofa For Office Reception with Backrest and Armrest",
     "specification": "3 Seater Sofa For Office Reception with caution and black colour."
    },
    {
     "proId": "p150",
     "image": "../Assests/furniturePhotos/3.jpeg",
     "sImages": "null",
     "oldPrice": 9895,
     "newPrice": 9395,
     "category": "table ",
     "sCategory": "FoldingTable",
     "stock": 54,
     "title": "Italica 9313 Chair",
     "description": "Supreme Omega Chair - Plastic Chair Design: Contemporary stackable design with premium and classy rattan-finish.",
     "specification": "Italica 8103 Chair - Outdoor Luxury Sunlounger Chair by Kylin"
    },
    {
     "proId": "p151",
     "image": "../Assests/furniturePhotos/4.jpeg",
     "sImages": "null",
     "oldPrice": 55562,
     "newPrice": 55062,
     "category": "wordrobe",
     "sCategory": "wordrobe",
     "stock": 45,
     "title": "Designer Italica Arm Chair with Steel Leg",
     "description": "Italica 8103 Chair - Outdoor Luxury Sunlounger Chair by Kylin",
     "specification": "3 Seater Sofa For Office Reception with caution and black colour."
    },
    {
     "proId": "p152",
     "image": "../Assests/furniturePhotos/5.jpeg",
     "sImages": "null",
     "oldPrice": 56665,
     "newPrice": 56165,
     "category": "bed ",
     "sCategory": "bed ",
     "stock": 54,
     "title": "Sun lounger Chair - Outdoor Luxury Sun lounger",
     "description": "This office sofa set comes with a geometric design. the brown sofa with a backrest and armrest you to experience superior comfort.",
     "specification": "This office sofa set comes with a geometric design. the brown sofa with a backrest and armrest you to experience superior comfort."
    },
    {
     "proId": "p153",
     "image": "../Assests/furniturePhotos/6.jpeg",
     "sImages": "null",
     "oldPrice": 26552,
     "newPrice": 26052,
     "category": "desk",
     "sCategory": "desk",
     "stock": 54,
     "title": "Italica Chair in Plastic Body",
     "description": "Best sofa For Office Reception with Backrest and Armrest",
     "specification": "3 Seater Sofa For Office Reception with caution and black colour."
    },
    {
     "proId": "p154",
     "image": "../Assests/furniturePhotos/7.jpeg",
     "sImages": "null",
     "oldPrice": 56202,
     "newPrice": 55702,
     "category": "bookcase",
     "sCategory": "bookcase",
     "stock": 54,
     "title": "Stainless Steel Dining Table",
     "description": "Italica Chair 2109: Designed specifically to support the vertebral column and to provide excellent lumbar support, the spine care series is the finest specimen of ergonomic design, aesthetics and comfort.",
     "specification": "Kylin Revolving Office Chair in Black - Fixed Handle - Mid-Back - Plastic Base, Net Seat and Back For Office, Workstation In Black Color."
    },
    {
     "proId": "p155",
     "image": "../Assests/furniturePhotos/8.jpeg",
     "sImages": "null",
     "oldPrice": 87004,
     "newPrice": 86504,
     "category": "chair",
     "sCategory": "Dinning Chair",
     "stock": 78,
     "title": "Best Outdoor Chair by Italica",
     "description": "This Couch Office - Couch for Office in Black",
     "specification": "3 Seater Sofa For Office Reception with caution and black colour."
    },
    {
     "proId": "p156",
     "image": "../Assests/furniturePhotos/9.jpeg",
     "sImages": "null",
     "oldPrice": 4541,
     "newPrice": 4041,
     "category": "table ",
     "sCategory": "table",
     "stock": 78,
     "title": "Italica 9313 Chair",
     "description": "Supreme Omega Chair - Plastic Chair Design: Contemporary stackable design with premium and classy rattan-finish.",
     "specification": "This office sofa set comes with a geometric design. the brown sofa with a backrest and armrest you to experience superior comfort."
    },
    {
     "proId": "p157",
     "image": "../Assests/furniturePhotos/10.jpeg",
     "sImages": "null",
     "oldPrice": 5562,
     "newPrice": 5062,
     "category": "wordrobe",
     "sCategory": "wordrobe",
     "stock": 54,
     "title": "Designer Italica Arm Chair with Steel Leg",
     "description": "Best sofa For Office Reception with Backrest and Armrest",
     "specification": "This office sofa set comes with a geometric design. the brown sofa with a backrest and armrest you to experience superior comfort."
    },
    {
     "proId": "p158",
     "image": "../Assests/furniturePhotos/11.jpeg",
     "sImages": "null",
     "oldPrice": 5265,
     "newPrice": 4765,
     "category": "bed ",
     "sCategory": "SofaBed",
     "stock": 66,
     "title": "Sun lounger Chair - Outdoor Luxury Sun lounger",
     "description": "Kylin Revolving Office Chair in Black - Fixed Handle - Mid-Back - Plastic Base, Net Seat and Back For Office, Workstation In Black Color.",
     "specification": "3 Seater Sofa For Office Reception with caution and black colour."
    },
    {
     "proId": "p161",
     "image": "../Assests/furniturePhotos/12.jpeg",
     "sImages": "null",
     "oldPrice": 1999,
     "newPrice": 1499,
     "category": "chair",
     "sCategory": "Stool",
     "stock": 545,
     "title": "Restaurant Dining Table for Restaurant",
     "description": "3 Seater Sofa For Office Reception with caution and black colour.",
     "specification": "Italica 8103 Chair - Outdoor Luxury Sunlounger Chair by Kylin"
    },
    {
     "proId": "p162",
     "image": "../Assests/furniturePhotos/13.jpeg",
     "sImages": "null",
     "oldPrice": 5999,
     "newPrice": 5499,
     "category": "table ",
     "sCategory": "table",
     "stock": 54,
     "title": "Italica Chair in Plastic Body",
     "description": "Kylin Revolving Office Chair in Black - Fixed Handle - Mid-Back - Plastic Base, Net Seat and Back For Office, Workstation In Black Color.",
     "specification": "3 Seater Sofa For Office Reception with caution and black colour."
    },
    {
     "proId": "p163",
     "image": "../Assests/furniturePhotos/14.jpeg",
     "sImages": "null",
     "oldPrice": 11999,
     "newPrice": 11499,
     "category": "wordrobe",
     "sCategory": "wordrobe",
     "stock": 45,
     "title": "Best Outdoor Chair by Italica",
     "description": "Italica 8103 Chair - Outdoor Luxury Sunlounger Chair by Kylin",
     "specification": "This office sofa set comes with a geometric design. the brown sofa with a backrest and armrest you to experience superior comfort."
    },
    {
     "proId": "p164",
     "image": "../Assests/furniturePhotos/15.jpeg",
     "sImages": "null",
     "oldPrice": 8922,
     "newPrice": 8422,
     "category": "bed ",
     "sCategory": "bed ",
     "stock": 54,
     "title": "Designer Italica Arm Chair with Steel Leg",
     "description": "3 Seater Sofa For Office Reception with caution and black colour.",
     "specification": "3 Seater Sofa For Office Reception with caution and black colour."
    },
    {
     "proId": "p167",
     "image": "../Assests/furniturePhotos/16.jpeg",
     "sImages": "null",
     "oldPrice": 56665,
     "newPrice": 56165,
     "category": "chair",
     "sCategory": "Arm Chair",
     "stock": 54,
     "title": "Italica 9313 Chair",
     "description": "This office sofa set comes with a geometric design. the brown sofa with a backrest and armrest you to experience superior comfort.",
     "specification": "Kylin Revolving Office Chair in Black - Fixed Handle - Mid-Back - Plastic Base, Net Seat and Back For Office, Workstation In Black Color."
    },
    {
     "proId": "p168",
     "image": "../Assests/furniturePhotos/17.jpeg",
     "sImages": "null",
     "oldPrice": 26552,
     "newPrice": 26052,
     "category": "table ",
     "sCategory": "FoldingTable",
     "stock": 54,
     "title": "Best Outdoor Chair by Italica",
     "description": "This office sofa set comes with a geometric design. the brown sofa with a backrest and armrest you to experience superior comfort.",
     "specification": "Best sofa For Office Reception with Backrest and Armrest"
    },
    {
     "proId": "p169",
     "image": "../Assests/furniturePhotos/18.jpeg",
     "sImages": "null",
     "oldPrice": 56202,
     "newPrice": 55702,
     "category": "wordrobe",
     "sCategory": "wordrobe",
     "stock": 78,
     "title": "Italica 9313 Chair",
     "description": "3 Seater Sofa For Office Reception with caution and black colour.",
     "specification": "Italica Chair 2109: Designed specifically to support the vertebral column and to provide excellent lumbar support, the spine care series is the finest specimen of ergonomic design, aesthetics and comfort."
    },
    {
     "proId": "p170",
     "image": "../Assests/furniturePhotos/19.jpeg",
     "sImages": "null",
     "oldPrice": 87004,
     "newPrice": 86504,
     "category": "bed ",
     "sCategory": "bed ",
     "stock": 78,
     "title": "Chair With Side Arms (Camel)",
     "description": "Italica 8103 Chair - Outdoor Luxury Sunlounger Chair by Kylin",
     "specification": "This office sofa set comes with a geometric design. the brown sofa with a backrest and armrest you to experience superior comfort."
    },
    {
     "proId": "p173",
     "image": "../Assests/furniturePhotos/20.jpeg",
     "sImages": "null",
     "oldPrice": 5265,
     "newPrice": 4765,
     "category": "chair",
     "sCategory": "Dinning Chair",
     "stock": 54,
     "title": "Italica Chair in Plastic Body",
     "description": "3 Seater Sofa For Office Reception with caution and black colour.",
     "specification": "3 Seater Sofa For Office Reception with caution and black colour."
    },
    {
     "proId": "p174",
     "image": "../Assests/furniturePhotos/21.jpeg",
     "sImages": "null",
     "oldPrice": 1546,
     "newPrice": 1046,
     "category": "table ",
     "sCategory": "table",
     "stock": 66,
     "title": "Italica Chair in Plastic Body",
     "description": "This office sofa set comes with a geometric design. the brown sofa with a backrest and armrest you to experience superior comfort.",
     "specification": "Writing pad fabric study chair - Best black cushion writing pad chair with half pad and designer looking fix arm pad chair in black colour"
    },
    {
     "proId": "p175",
     "image": "../Assests/furniturePhotos/22.jpeg",
     "sImages": "null",
     "oldPrice": 4650,
     "newPrice": 4150,
     "category": "wordrobe",
     "sCategory": "wordrobe",
     "stock": 545,
     "title": "Stainless Steel Dining Table",
     "description": "3 Seater Sofa For Office Reception with caution and black colour.",
     "specification": "Disc Supreme Restaurant Round Table.  pad chair with half pad and designer looking fix arm pad chair in black colour"
    },
    {
     "proId": "p176",
     "image": "../Assests/furniturePhotos/23.jpeg",
     "sImages": "null",
     "oldPrice": 1999,
     "newPrice": 1499,
     "category": "bed ",
     "sCategory": "SofaBed",
     "stock": 54,
     "title": "Best Outdoor Chair by Italica",
     "description": "Kylin Revolving Office Chair in Black - Fixed Handle - Mid-Back - Plastic Base, Net Seat and Back For Office, Workstation In Black Color.",
     "specification": "This Couch Office - Couch for Office in Black"
    },
    {
     "proId": "p179",
     "image": "../Assests/furniturePhotos/24.jpeg",
     "sImages": "null",
     "oldPrice": 8922,
     "newPrice": 8422,
     "category": "chair",
     "sCategory": "Stool",
     "stock": 45,
     "title": "Italica Chair in Plastic Body",
     "description": "Best sofa For Office Reception with Backrest and Armrest",
     "specification": "Italica Chair 2109: Designed specifically to support the vertebral column and to provide excellent lumbar support, the spine care series is the finest specimen of ergonomic design, aesthetics and comfort."
    },
    {
     "proId": "p180",
     "image": "../Assests/furniturePhotos/25.jpeg",
     "sImages": "null",
     "oldPrice": 9895,
     "newPrice": 9395,
     "category": "table ",
     "sCategory": "table",
     "stock": 54,
     "title": "Designer Italica Arm Chair with Steel Leg",
     "description": "Italica Chair 2109: Designed specifically to support the vertebral column and to provide excellent lumbar support, the spine care series is the finest specimen of ergonomic design, aesthetics and comfort.",
     "specification": "This office sofa set comes with a geometric design. the brown sofa with a backrest and armrest you to experience superior comfort."
    },
    {
     "proId": "p181",
     "image": "../Assests/furniturePhotos/26.jpeg",
     "sImages": "null",
     "oldPrice": 55562,
     "newPrice": 55062,
     "category": "wordrobe",
     "sCategory": "wordrobe",
     "stock": 54,
     "title": "Sun lounger Chair - Outdoor Luxury Sun lounger",
     "description": "This office sofa set comes with a geometric design. the brown sofa with a backrest and armrest you to experience superior comfort.",
     "specification": "3 Seater Sofa For Office Reception with caution and black colour."
    },
    {
     "proId": "p182",
     "image": "../Assests/furniturePhotos/27.jpeg",
     "sImages": "null",
     "oldPrice": 56665,
     "newPrice": 56165,
     "category": "bed ",
     "sCategory": "bed ",
     "stock": 54,
     "title": "Restaurant Dining Table for Restaurant",
     "description": "3 Seater Sofa For Office Reception with caution and black colour.",
     "specification": "This office sofa set comes with a geometric design. the brown sofa with a backrest and armrest you to experience superior comfort."
    },
    {
     "proId": "p185",
     "image": "../Assests/furniturePhotos/28.jpeg",
     "sImages": "null",
     "oldPrice": 87004,
     "newPrice": 86504,
     "category": "chair",
     "sCategory": "Dinning Chair",
     "stock": 78,
     "title": "Chair With Side Arms (Camel)",
     "description": "Kylin Revolving Office Chair in Black - Fixed Handle - Mid-Back - Plastic Base, Net Seat and Back For Office, Workstation In Black Color.",
     "specification": "This office sofa set comes with a geometric design. the brown sofa with a backrest and armrest you to experience superior comfort."
    },
    {
     "proId": "p186",
     "image": "../Assests/furniturePhotos/29.jpeg",
     "sImages": "null",
     "oldPrice": 4541,
     "newPrice": 4041,
     "category": "table ",
     "sCategory": "FoldingTable",
     "stock": 78,
     "title": "Sun lounger Chair ",
     "description": "This office sofa set comes with a geometric design. the brown sofa with a backrest and armrest you to experience superior comfort.",
     "specification": "3 Seater Sofa For Office Reception with caution and black colour."
    },
    {
     "proId": "p187",
     "image": "../Assests/furniturePhotos/30.jpeg",
     "sImages": "null",
     "oldPrice": 5562,
     "newPrice": 5062,
     "category": "wordrobe",
     "sCategory": "wordrobe",
     "stock": 54,
     "title": "Italica 9313 Chair",
     "description": "Italica 8103 Chair - Outdoor Luxury Sunlounger Chair by Kylin",
     "specification": "Italica 8103 Chair - Outdoor Luxury Sunlounger Chair by Kylin"
    },
    {
     "proId": "p188",
     "image": "../Assests/furniturePhotos/31.jpeg",
     "sImages": "null",
     "oldPrice": 5265,
     "newPrice": 4765,
     "category": "bed ",
     "sCategory": "bed ",
     "stock": 66,
     "title": "Italica Chair in Plastic Body",
     "description": "This office sofa set comes with a geometric design. the brown sofa with a backrest and armrest you to experience superior comfort.",
     "specification": "3 Seater Sofa For Office Reception with caution and black colour."
    },
    {
     "proId": "p191",
     "image": "../Assests/furniturePhotos/32.jpeg",
     "sImages": "null",
     "oldPrice": 1999,
     "newPrice": 1499,
     "category": "chair",
     "sCategory": "Dinning Chair",
     "stock": 545,
     "title": "Sun lounger Chair ",
     "description": "3 Seater Sofa For Office Reception with caution and black colour.",
     "specification": "This office sofa set comes with a geometric design. the brown sofa with a backrest and armrest you to experience superior comfort."
    },
    {
     "proId": "p192",
     "image": "../Assests/furniturePhotos/33.jpeg",
     "sImages": "null",
     "oldPrice": 5999,
     "newPrice": 5499,
     "category": "table ",
     "sCategory": "FoldingTable",
     "stock": 54,
     "title": "Sun lounger Chair - Outdoor Luxury Sun lounger",
     "description": "3 Seater Sofa For Office Reception with caution and black colour.",
     "specification": "3 Seater Sofa For Office Reception with caution and black colour."
    },
    {
     "proId": "p193",
     "image": "../Assests/furniturePhotos/34.jpeg",
     "sImages": "null",
     "oldPrice": 11999,
     "newPrice": 11499,
     "category": "wordrobe",
     "sCategory": "wordrobe",
     "stock": 45,
     "title": "Sun lounger Chair ",
     "description": "Italica 8103 Chair - Outdoor Luxury Sunlounger Chair by Kylin",
     "specification": "Kylin Revolving Office Chair in Black - Fixed Handle - Mid-Back - Plastic Base, Net Seat and Back For Office, Workstation In Black Color."
    },
    {
     "proId": "p194",
     "image": "../Assests/furniturePhotos/35.jpeg",
     "sImages": "null",
     "oldPrice": 8922,
     "newPrice": 8422,
     "category": "bed ",
     "sCategory": "bed ",
     "stock": 54,
     "title": "Designer Italica Arm Chair with Steel Leg",
     "description": "This office sofa set comes with a geometric design. the brown sofa with a backrest and armrest you to experience superior comfort.",
     "specification": "Best sofa For Office Reception with Backrest and Armrest"
    },
    {
     "proId": "p197",
     "image": "../Assests/furniturePhotos/36.jpeg",
     "sImages": "null",
     "oldPrice": 56665,
     "newPrice": 56165,
     "category": "chair",
     "sCategory": "Stool",
     "stock": 54,
     "title": "Italica Chair in Plastic Body",
     "description": "3 Seater Sofa For Office Reception with caution and black colour.",
     "specification": "Italica Chair 2109: Designed specifically to support the vertebral column and to provide excellent lumbar support, the spine care series is the finest specimen of ergonomic design, aesthetics and comfort."
    },
    {
     "proId": "p198",
     "image": "../Assests/furniturePhotos/37.jpeg",
     "sImages": "null",
     "oldPrice": 26552,
     "newPrice": 26052,
     "category": "table ",
     "sCategory": "FoldingTable",
     "stock": 54,
     "title": "Sun lounger Chair ",
     "description": "Best sofa For Office Reception with Backrest and Armrest",
     "specification": "This office sofa set comes with a geometric design. the brown sofa with a backrest and armrest you to experience superior comfort."
    },
    {
     "proId": "p199",
     "image": "../Assests/furniturePhotos/38.jpeg",
     "sImages": "null",
     "oldPrice": 56202,
     "newPrice": 55702,
     "category": "wordrobe",
     "sCategory": "wordrobe",
     "stock": 78,
     "title": "Italica Chair in Plastic Body",
     "description": "Italica 8103 Chair - Outdoor Luxury Sunlounger Chair by Kylin",
     "specification": "3 Seater Sofa For Office Reception with caution and black colour."
    },
    {
     "proId": "p200",
     "image": "../Assests/furniturePhotos/39.jpeg",
     "sImages": "null",
     "oldPrice": 87004,
     "newPrice": 86504,
     "category": "bed ",
     "sCategory": "SofaBed",
     "stock": 78,
     "title": "Sun lounger Chair - Outdoor Luxury Sun lounger",
     "description": "This office sofa set comes with a geometric design. the brown sofa with a backrest and armrest you to experience superior comfort.",
     "specification": "New design flexible writing board chair with cushion blue seating and flexible wooden writing pad."
    },
    {
     "proId": "p203",
     "image": "../Assests/furniturePhotos/40.jpeg",
     "sImages": "null",
     "oldPrice": 5265,
     "newPrice": 4765,
     "category": "chair",
     "sCategory": "Dinning Chair",
     "stock": 54,
     "title": "Sun lounger Chair ",
     "description": "3 Seater Sofa For Office Reception with caution and black colour.",
     "specification": "Writing pad fabric study chair - Best black cushion writing pad chair with half pad and designer looking fix arm pad chair in black colour"
    },
    {
     "proId": "p204",
     "image": "../Assests/furniturePhotos/41.jpeg",
     "sImages": "null",
     "oldPrice": 1546,
     "newPrice": 1046,
     "category": "table ",
     "sCategory": "FoldingTable",
     "stock": 66,
     "title": "Designer Italica Arm Chair with Steel Leg",
     "description": "This office sofa set comes with a geometric design. the brown sofa with a backrest and armrest you to experience superior comfort.",
     "specification": "Study Chair with Writing Pad Folding arm, cushion seat, chrome frame half brown writing pad plastic withholding stuff under the chair."
    },
    {
     "proId": "p205",
     "image": "../Assests/furniturePhotos/42.jpeg",
     "sImages": "null",
     "oldPrice": 4650,
     "newPrice": 4150,
     "category": "wordrobe",
     "sCategory": "wordrobe",
     "stock": 545,
     "title": "Restaurant Dining Table for Restaurant",
     "description": "Italica 8103 Chair - Outdoor Luxury Sunlounger Chair by Kylin",
     "specification": "New design flexible writing board chair with cushion blue seating and flexible wooden writing pad."
    }
   ]


   export default Data;